title: Apollo
description: Apollo is a MOOSE-based application created for the scalable solution of finite element electromagnetics problems
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

color_scheme: dark
